Validates all logs
ONDC-Official/v1.2.0-logs pull request #1264
Opened 2024-04-02 12:09 UTC by amitkbadheka

Solved all issues mentioned in - https://github.com/ONDC-Official/v1.2.0-logs/issues/1144

Have validated all the logs using the log validation tool.

2024-04-03 09:29 UTC, sandeepshahi requested changes
@amitkbadheka, could you please submit the logs with separate JSONs for each payload. The submitted flows are ready-to-test with utility version.

2024-04-03 09:41 UTC, amitkbadheka commented
Sure. I will submit it individually.

2024-04-03 10:16 UTC, amitkbadheka commented
Hey, I have separated the files

2024-04-04 07:08 UTC, sandeepshahi approved these changes

2024-04-04 07:08 UTC, merged