Mystore F&B buyer app logs
ONDC-Official/v1.2.0-logs pull request #1969
Opened 2024-07-02 07:47 UTC by dharkum24

Mystore F&B buyer app logs

2024-07-02 08:16 UTC, sandeepshahi requested changes
Is the utility report clean for all the flows?

@dharkum24

2024-07-02 08:23 UTC, dharkum24 commented
> Is the utility report clean for all the flows?
> 
> @dharkum24

@sandeepshahi From **Buyer** side we are good. We tried with different sellers but didn't get enough response from them. We got some help from Esamudaay and we completed flows

2024-07-03 12:41 UTC, dharkum24 commented
@sandeepshahi Can you please merge and review cc:-  @asifrazastorehippo

2024-07-04 06:00 UTC, sandeepshahi approved these changes

2024-07-04 06:00 UTC, merged