DIGILEDGE Seller App RET11 flow 1 logs submitted
ONDC-Official/v1.2.0-logs pull request #2013
Opened 2024-07-09 06:24 UTC by shabirahamed

2024-07-11 06:07 UTC, sandeepshahi requested changes
@shabirahamed, flow 5 and 6 must also be submitted for verification.

2024-07-11 06:11 UTC, shabirahamed commented
We are working on the flow 5 and flow 6 logs. Once it's done will update the same

2024-07-18 04:47 UTC, shabirahamed commented
I have submitted all the flows.
 could you please review the RET11 logs.

@sandeepshahi

2024-07-22 04:21 UTC, sandeepshahi approved these changes

2024-07-22 04:21 UTC, merged