feat: added logs for eNAM agri and retail logs
ONDC-Official/v1.2.0-logs pull request #2270
Opened 2024-08-17 06:53 UTC by vishalbitxia

2024-08-28 04:51 UTC, sandeepshahi requested changes
@vishalbitxia, are the log validation utility reports clear for all the flows of retail (online payment)?

2024-09-05 13:58 UTC, vishalbitxia commented
> @vishalbitxia, are the log validation utility reports clear for all the flows of retail (online payment)?

We ran log verification utility on the retail logs and identified a few issues. We have fixed those and resubmitted the logs. Rest of the issues do not appear to be actual problems. These issues are documented in and excel which is shared over email by Vibhav.

2024-09-09 10:29 UTC, vibhav-bitxia commented
@sandeepshahi Please verify the logs we have submitted

2024-09-13 05:41 UTC, sandeepshahi approved these changes

2024-09-13 05:41 UTC, merged