Logs submitted as per sandeep comment
ONDC-Official/v1.2.0-logs pull request #2846
Opened 2024-12-02 06:56 UTC by kanagasathish

1. We are the seller , as we discussed with you ondc team they told for seller no need for catlog rejection flow
2. Each flow added the file with log validation utility response
3. Submitted with seperate payloads for each flow

2024-12-02 12:27 UTC, kanagasathish commented
Added Pramaan catalogue rejection flow log also

2024-12-03 05:34 UTC, kanagasathish commented
sandeep waiting for your review please reply

2024-12-03 11:56 UTC, sandeepshahi requested changes
@kanagasathish, please remove the unwanted files outside your NP folder.

- All the applicable flows of IGM should be submitted along with RSF logs for verification.

2024-12-03 11:57 UTC, sandeepshahi commented
@kanagasathish, for retail core (flow 1 to 6), please fix the above issues and share the POC details (email id) for communication.

2024-12-03 11:57 UTC, closed without merging

2024-12-03 13:29 UTC, kanagasathish commented
> @kanagasathish, for retail core (flow 1 to 6), please fix the above issues and share the POC details (email id) for communication.

kanagavalli.a@betamonks.com