Fix logs
ONDC-Official/v1.2.0-logs pull request #3009
Opened 2024-12-30 11:34 UTC by ftbits

Fixes issues found in the first log review.

2024-12-30 12:14 UTC, sandeepshahi requested changes
@ftbits, please submit [log validation utility](https://github.com/ONDC-Official/log-validation-utility) report for all the flows; 

Also, review and resolve all the applicable items in the list of [manual validations](https://docs.google.com/document/d/1ROAGXqj5cJkgsNWvg_xiufglhqEQDJFBgQSPcFZMZd4/edit?tab=t.0) on your system before submitting logs for technical review.

2025-01-02 10:49 UTC, sandeepshahi requested changes
Please fix the issues identified by the utility and submit the logs only if the utility report is clear, or if the issues are limited to the counterparty.

@ftbits

2025-01-02 10:49 UTC, closed without merging

2025-01-06 09:10 UTC, timothegenzmer commented on Plantix/buyer-app/log-verification-utility/flow-2-resp.json
> +                "schemaErr0": "/message/order/quote/breakup/0 must have required property '@ondc/org/item_id'",
missing properties in on_init

2025-01-06 09:12 UTC, timothegenzmer commented on Plantix/buyer-app/log-verification-utility/flow-2-resp.json
> +                "quoteErr0": "Mismatch found for item with item_id WkM0I3RIFbcHeLJxUceY while comparing quote object of on_select and confirm",
we need to send the values received in on_select

2025-01-06 09:15 UTC, timothegenzmer commented on Plantix/buyer-app/log-verification-utility/flow-3-resp.json
>                  "bapGstTags": "Tags/bap_terms should have valid gst number and fields in /confirm",
in pre-prod we can provide dummy value